name: autotools-cross-compile-example
version: "1.0"
summary: An example snap for an cross-compiled autotools project
description: |
  Shows how to create a snap for an application that uses a autotools for
  cross-compiling and installation.

grade: devel
base: core22
confinement: strict

# Only specify cross-compilation from one architecture to another.
architectures:
  - build-on: amd64
    build-for: arm64

lint:
  ignore:
    - library

apps:
  # Using the name of the snap as the key name allows the program to be invoked by its name.
  autotools-cross-compile-example:
    command: usr/bin/autotools-cross-compile-example

parts:
  cross-compilation-part:
    plugin: autotools
    source: .
    autotools-configure-parameters:
      - --prefix=/usr
      - --host=${SNAPCRAFT_ARCH_TRIPLET}
    build-packages:
      - on amd64 to arm64:
        - gcc-aarch64-linux-gnu 
        - binutils-aarch64-linux-gnu
        - libc6-dev-arm64-cross
#        - libc6-arm64-cross
